# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/weihai/coco

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/weihai/coco

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/weihai/coco/CMakeFiles /home/weihai/coco//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/weihai/coco/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named testDatabaseTableID

# Build rule for target.
testDatabaseTableID: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testDatabaseTableID
.PHONY : testDatabaseTableID

# fast build rule for target.
testDatabaseTableID/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDatabaseTableID.dir/build.make CMakeFiles/testDatabaseTableID.dir/build
.PHONY : testDatabaseTableID/fast

#=============================================================================
# Target rules for targets named testTPCCDatabase

# Build rule for target.
testTPCCDatabase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTPCCDatabase
.PHONY : testTPCCDatabase

# fast build rule for target.
testTPCCDatabase/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCDatabase.dir/build.make CMakeFiles/testTPCCDatabase.dir/build
.PHONY : testTPCCDatabase/fast

#=============================================================================
# Target rules for targets named testTPCCQuery

# Build rule for target.
testTPCCQuery: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTPCCQuery
.PHONY : testTPCCQuery

# fast build rule for target.
testTPCCQuery/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCQuery.dir/build.make CMakeFiles/testTPCCQuery.dir/build
.PHONY : testTPCCQuery/fast

#=============================================================================
# Target rules for targets named testTPCCRandom

# Build rule for target.
testTPCCRandom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTPCCRandom
.PHONY : testTPCCRandom

# fast build rule for target.
testTPCCRandom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCRandom.dir/build.make CMakeFiles/testTPCCRandom.dir/build
.PHONY : testTPCCRandom/fast

#=============================================================================
# Target rules for targets named testTPCCSchema

# Build rule for target.
testTPCCSchema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTPCCSchema
.PHONY : testTPCCSchema

# fast build rule for target.
testTPCCSchema/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCSchema.dir/build.make CMakeFiles/testTPCCSchema.dir/build
.PHONY : testTPCCSchema/fast

#=============================================================================
# Target rules for targets named testTPCCTransaction

# Build rule for target.
testTPCCTransaction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTPCCTransaction
.PHONY : testTPCCTransaction

# fast build rule for target.
testTPCCTransaction/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCTransaction.dir/build.make CMakeFiles/testTPCCTransaction.dir/build
.PHONY : testTPCCTransaction/fast

#=============================================================================
# Target rules for targets named testYCSBDatabase

# Build rule for target.
testYCSBDatabase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testYCSBDatabase
.PHONY : testYCSBDatabase

# fast build rule for target.
testYCSBDatabase/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBDatabase.dir/build.make CMakeFiles/testYCSBDatabase.dir/build
.PHONY : testYCSBDatabase/fast

#=============================================================================
# Target rules for targets named testYCSBQuery

# Build rule for target.
testYCSBQuery: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testYCSBQuery
.PHONY : testYCSBQuery

# fast build rule for target.
testYCSBQuery/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBQuery.dir/build.make CMakeFiles/testYCSBQuery.dir/build
.PHONY : testYCSBQuery/fast

#=============================================================================
# Target rules for targets named testYCSBRandom

# Build rule for target.
testYCSBRandom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testYCSBRandom
.PHONY : testYCSBRandom

# fast build rule for target.
testYCSBRandom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBRandom.dir/build.make CMakeFiles/testYCSBRandom.dir/build
.PHONY : testYCSBRandom/fast

#=============================================================================
# Target rules for targets named testYCSBSchema

# Build rule for target.
testYCSBSchema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testYCSBSchema
.PHONY : testYCSBSchema

# fast build rule for target.
testYCSBSchema/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBSchema.dir/build.make CMakeFiles/testYCSBSchema.dir/build
.PHONY : testYCSBSchema/fast

#=============================================================================
# Target rules for targets named testYCSBTransaction

# Build rule for target.
testYCSBTransaction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testYCSBTransaction
.PHONY : testYCSBTransaction

# fast build rule for target.
testYCSBTransaction/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBTransaction.dir/build.make CMakeFiles/testYCSBTransaction.dir/build
.PHONY : testYCSBTransaction/fast

#=============================================================================
# Target rules for targets named testEncoder

# Build rule for target.
testEncoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testEncoder
.PHONY : testEncoder

# fast build rule for target.
testEncoder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testEncoder.dir/build.make CMakeFiles/testEncoder.dir/build
.PHONY : testEncoder/fast

#=============================================================================
# Target rules for targets named testFixedString

# Build rule for target.
testFixedString: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testFixedString
.PHONY : testFixedString

# fast build rule for target.
testFixedString/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testFixedString.dir/build.make CMakeFiles/testFixedString.dir/build
.PHONY : testFixedString/fast

#=============================================================================
# Target rules for targets named testHashMap

# Build rule for target.
testHashMap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testHashMap
.PHONY : testHashMap

# fast build rule for target.
testHashMap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testHashMap.dir/build.make CMakeFiles/testHashMap.dir/build
.PHONY : testHashMap/fast

#=============================================================================
# Target rules for targets named testLockfreeQueue

# Build rule for target.
testLockfreeQueue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testLockfreeQueue
.PHONY : testLockfreeQueue

# fast build rule for target.
testLockfreeQueue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testLockfreeQueue.dir/build.make CMakeFiles/testLockfreeQueue.dir/build
.PHONY : testLockfreeQueue/fast

#=============================================================================
# Target rules for targets named testMVCCHashMap

# Build rule for target.
testMVCCHashMap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testMVCCHashMap
.PHONY : testMVCCHashMap

# fast build rule for target.
testMVCCHashMap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testMVCCHashMap.dir/build.make CMakeFiles/testMVCCHashMap.dir/build
.PHONY : testMVCCHashMap/fast

#=============================================================================
# Target rules for targets named testMessage

# Build rule for target.
testMessage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testMessage
.PHONY : testMessage

# fast build rule for target.
testMessage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testMessage.dir/build.make CMakeFiles/testMessage.dir/build
.PHONY : testMessage/fast

#=============================================================================
# Target rules for targets named testPercentile

# Build rule for target.
testPercentile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testPercentile
.PHONY : testPercentile

# fast build rule for target.
testPercentile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testPercentile.dir/build.make CMakeFiles/testPercentile.dir/build
.PHONY : testPercentile/fast

#=============================================================================
# Target rules for targets named testRandom

# Build rule for target.
testRandom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testRandom
.PHONY : testRandom

# fast build rule for target.
testRandom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testRandom.dir/build.make CMakeFiles/testRandom.dir/build
.PHONY : testRandom/fast

#=============================================================================
# Target rules for targets named testSerialization

# Build rule for target.
testSerialization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testSerialization
.PHONY : testSerialization

# fast build rule for target.
testSerialization/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSerialization.dir/build.make CMakeFiles/testSerialization.dir/build
.PHONY : testSerialization/fast

#=============================================================================
# Target rules for targets named testSocket

# Build rule for target.
testSocket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testSocket
.PHONY : testSocket

# fast build rule for target.
testSocket/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSocket.dir/build.make CMakeFiles/testSocket.dir/build
.PHONY : testSocket/fast

#=============================================================================
# Target rules for targets named testSpinLock

# Build rule for target.
testSpinLock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testSpinLock
.PHONY : testSpinLock

# fast build rule for target.
testSpinLock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSpinLock.dir/build.make CMakeFiles/testSpinLock.dir/build
.PHONY : testSpinLock/fast

#=============================================================================
# Target rules for targets named testStringPiece

# Build rule for target.
testStringPiece: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testStringPiece
.PHONY : testStringPiece

# fast build rule for target.
testStringPiece/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testStringPiece.dir/build.make CMakeFiles/testStringPiece.dir/build
.PHONY : testStringPiece/fast

#=============================================================================
# Target rules for targets named testTime

# Build rule for target.
testTime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTime
.PHONY : testTime

# fast build rule for target.
testTime/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTime.dir/build.make CMakeFiles/testTime.dir/build
.PHONY : testTime/fast

#=============================================================================
# Target rules for targets named testZipf

# Build rule for target.
testZipf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testZipf
.PHONY : testZipf

# fast build rule for target.
testZipf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testZipf.dir/build.make CMakeFiles/testZipf.dir/build
.PHONY : testZipf/fast

#=============================================================================
# Target rules for targets named testCoordinator

# Build rule for target.
testCoordinator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testCoordinator
.PHONY : testCoordinator

# fast build rule for target.
testCoordinator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCoordinator.dir/build.make CMakeFiles/testCoordinator.dir/build
.PHONY : testCoordinator/fast

#=============================================================================
# Target rules for targets named testExecutor

# Build rule for target.
testExecutor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testExecutor
.PHONY : testExecutor

# fast build rule for target.
testExecutor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testExecutor.dir/build.make CMakeFiles/testExecutor.dir/build
.PHONY : testExecutor/fast

#=============================================================================
# Target rules for targets named testPartitioner

# Build rule for target.
testPartitioner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testPartitioner
.PHONY : testPartitioner

# fast build rule for target.
testPartitioner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testPartitioner.dir/build.make CMakeFiles/testPartitioner.dir/build
.PHONY : testPartitioner/fast

#=============================================================================
# Target rules for targets named testTable

# Build rule for target.
testTable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTable
.PHONY : testTable

# fast build rule for target.
testTable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTable.dir/build.make CMakeFiles/testTable.dir/build
.PHONY : testTable/fast

#=============================================================================
# Target rules for targets named testReservation

# Build rule for target.
testReservation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testReservation
.PHONY : testReservation

# fast build rule for target.
testReservation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testReservation.dir/build.make CMakeFiles/testReservation.dir/build
.PHONY : testReservation/fast

#=============================================================================
# Target rules for targets named testScarHelper

# Build rule for target.
testScarHelper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testScarHelper
.PHONY : testScarHelper

# fast build rule for target.
testScarHelper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testScarHelper.dir/build.make CMakeFiles/testScarHelper.dir/build
.PHONY : testScarHelper/fast

#=============================================================================
# Target rules for targets named testScarRWKey

# Build rule for target.
testScarRWKey: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testScarRWKey
.PHONY : testScarRWKey

# fast build rule for target.
testScarRWKey/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testScarRWKey.dir/build.make CMakeFiles/testScarRWKey.dir/build
.PHONY : testScarRWKey/fast

#=============================================================================
# Target rules for targets named testSiloRWKey

# Build rule for target.
testSiloRWKey: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testSiloRWKey
.PHONY : testSiloRWKey

# fast build rule for target.
testSiloRWKey/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSiloRWKey.dir/build.make CMakeFiles/testSiloRWKey.dir/build
.PHONY : testSiloRWKey/fast

#=============================================================================
# Target rules for targets named testTwoPLHelper

# Build rule for target.
testTwoPLHelper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTwoPLHelper
.PHONY : testTwoPLHelper

# fast build rule for target.
testTwoPLHelper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTwoPLHelper.dir/build.make CMakeFiles/testTwoPLHelper.dir/build
.PHONY : testTwoPLHelper/fast

#=============================================================================
# Target rules for targets named testTwoPLRWKey

# Build rule for target.
testTwoPLRWKey: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testTwoPLRWKey
.PHONY : testTwoPLRWKey

# fast build rule for target.
testTwoPLRWKey/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTwoPLRWKey.dir/build.make CMakeFiles/testTwoPLRWKey.dir/build
.PHONY : testTwoPLRWKey/fast

#=============================================================================
# Target rules for targets named testJemalloc

# Build rule for target.
testJemalloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testJemalloc
.PHONY : testJemalloc

# fast build rule for target.
testJemalloc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testJemalloc.dir/build.make CMakeFiles/testJemalloc.dir/build
.PHONY : testJemalloc/fast

#=============================================================================
# Target rules for targets named bench_tpcc

# Build rule for target.
bench_tpcc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_tpcc
.PHONY : bench_tpcc

# fast build rule for target.
bench_tpcc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_tpcc.dir/build.make CMakeFiles/bench_tpcc.dir/build
.PHONY : bench_tpcc/fast

#=============================================================================
# Target rules for targets named bench_ycsb

# Build rule for target.
bench_ycsb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_ycsb
.PHONY : bench_ycsb

# fast build rule for target.
bench_ycsb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_ycsb.dir/build.make CMakeFiles/bench_ycsb.dir/build
.PHONY : bench_ycsb/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest.dir/build.make googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

bench_tpcc.o: bench_tpcc.cpp.o
.PHONY : bench_tpcc.o

# target to build an object file
bench_tpcc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_tpcc.dir/build.make CMakeFiles/bench_tpcc.dir/bench_tpcc.cpp.o
.PHONY : bench_tpcc.cpp.o

bench_tpcc.i: bench_tpcc.cpp.i
.PHONY : bench_tpcc.i

# target to preprocess a source file
bench_tpcc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_tpcc.dir/build.make CMakeFiles/bench_tpcc.dir/bench_tpcc.cpp.i
.PHONY : bench_tpcc.cpp.i

bench_tpcc.s: bench_tpcc.cpp.s
.PHONY : bench_tpcc.s

# target to generate assembly for a file
bench_tpcc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_tpcc.dir/build.make CMakeFiles/bench_tpcc.dir/bench_tpcc.cpp.s
.PHONY : bench_tpcc.cpp.s

bench_ycsb.o: bench_ycsb.cpp.o
.PHONY : bench_ycsb.o

# target to build an object file
bench_ycsb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_ycsb.dir/build.make CMakeFiles/bench_ycsb.dir/bench_ycsb.cpp.o
.PHONY : bench_ycsb.cpp.o

bench_ycsb.i: bench_ycsb.cpp.i
.PHONY : bench_ycsb.i

# target to preprocess a source file
bench_ycsb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_ycsb.dir/build.make CMakeFiles/bench_ycsb.dir/bench_ycsb.cpp.i
.PHONY : bench_ycsb.cpp.i

bench_ycsb.s: bench_ycsb.cpp.s
.PHONY : bench_ycsb.s

# target to generate assembly for a file
bench_ycsb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_ycsb.dir/build.make CMakeFiles/bench_ycsb.dir/bench_ycsb.cpp.s
.PHONY : bench_ycsb.cpp.s

common/Time.o: common/Time.cpp.o
.PHONY : common/Time.o

# target to build an object file
common/Time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/common/Time.cpp.o
.PHONY : common/Time.cpp.o

common/Time.i: common/Time.cpp.i
.PHONY : common/Time.i

# target to preprocess a source file
common/Time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/common/Time.cpp.i
.PHONY : common/Time.cpp.i

common/Time.s: common/Time.cpp.s
.PHONY : common/Time.s

# target to generate assembly for a file
common/Time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/common/Time.cpp.s
.PHONY : common/Time.cpp.s

test/benchmark/testDatabaseTableID.o: test/benchmark/testDatabaseTableID.cpp.o
.PHONY : test/benchmark/testDatabaseTableID.o

# target to build an object file
test/benchmark/testDatabaseTableID.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDatabaseTableID.dir/build.make CMakeFiles/testDatabaseTableID.dir/test/benchmark/testDatabaseTableID.cpp.o
.PHONY : test/benchmark/testDatabaseTableID.cpp.o

test/benchmark/testDatabaseTableID.i: test/benchmark/testDatabaseTableID.cpp.i
.PHONY : test/benchmark/testDatabaseTableID.i

# target to preprocess a source file
test/benchmark/testDatabaseTableID.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDatabaseTableID.dir/build.make CMakeFiles/testDatabaseTableID.dir/test/benchmark/testDatabaseTableID.cpp.i
.PHONY : test/benchmark/testDatabaseTableID.cpp.i

test/benchmark/testDatabaseTableID.s: test/benchmark/testDatabaseTableID.cpp.s
.PHONY : test/benchmark/testDatabaseTableID.s

# target to generate assembly for a file
test/benchmark/testDatabaseTableID.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDatabaseTableID.dir/build.make CMakeFiles/testDatabaseTableID.dir/test/benchmark/testDatabaseTableID.cpp.s
.PHONY : test/benchmark/testDatabaseTableID.cpp.s

test/benchmark/tpcc/testTPCCDatabase.o: test/benchmark/tpcc/testTPCCDatabase.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCDatabase.o

# target to build an object file
test/benchmark/tpcc/testTPCCDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCDatabase.dir/build.make CMakeFiles/testTPCCDatabase.dir/test/benchmark/tpcc/testTPCCDatabase.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCDatabase.cpp.o

test/benchmark/tpcc/testTPCCDatabase.i: test/benchmark/tpcc/testTPCCDatabase.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCDatabase.i

# target to preprocess a source file
test/benchmark/tpcc/testTPCCDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCDatabase.dir/build.make CMakeFiles/testTPCCDatabase.dir/test/benchmark/tpcc/testTPCCDatabase.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCDatabase.cpp.i

test/benchmark/tpcc/testTPCCDatabase.s: test/benchmark/tpcc/testTPCCDatabase.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCDatabase.s

# target to generate assembly for a file
test/benchmark/tpcc/testTPCCDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCDatabase.dir/build.make CMakeFiles/testTPCCDatabase.dir/test/benchmark/tpcc/testTPCCDatabase.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCDatabase.cpp.s

test/benchmark/tpcc/testTPCCQuery.o: test/benchmark/tpcc/testTPCCQuery.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCQuery.o

# target to build an object file
test/benchmark/tpcc/testTPCCQuery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCQuery.dir/build.make CMakeFiles/testTPCCQuery.dir/test/benchmark/tpcc/testTPCCQuery.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCQuery.cpp.o

test/benchmark/tpcc/testTPCCQuery.i: test/benchmark/tpcc/testTPCCQuery.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCQuery.i

# target to preprocess a source file
test/benchmark/tpcc/testTPCCQuery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCQuery.dir/build.make CMakeFiles/testTPCCQuery.dir/test/benchmark/tpcc/testTPCCQuery.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCQuery.cpp.i

test/benchmark/tpcc/testTPCCQuery.s: test/benchmark/tpcc/testTPCCQuery.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCQuery.s

# target to generate assembly for a file
test/benchmark/tpcc/testTPCCQuery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCQuery.dir/build.make CMakeFiles/testTPCCQuery.dir/test/benchmark/tpcc/testTPCCQuery.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCQuery.cpp.s

test/benchmark/tpcc/testTPCCRandom.o: test/benchmark/tpcc/testTPCCRandom.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCRandom.o

# target to build an object file
test/benchmark/tpcc/testTPCCRandom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCRandom.dir/build.make CMakeFiles/testTPCCRandom.dir/test/benchmark/tpcc/testTPCCRandom.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCRandom.cpp.o

test/benchmark/tpcc/testTPCCRandom.i: test/benchmark/tpcc/testTPCCRandom.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCRandom.i

# target to preprocess a source file
test/benchmark/tpcc/testTPCCRandom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCRandom.dir/build.make CMakeFiles/testTPCCRandom.dir/test/benchmark/tpcc/testTPCCRandom.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCRandom.cpp.i

test/benchmark/tpcc/testTPCCRandom.s: test/benchmark/tpcc/testTPCCRandom.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCRandom.s

# target to generate assembly for a file
test/benchmark/tpcc/testTPCCRandom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCRandom.dir/build.make CMakeFiles/testTPCCRandom.dir/test/benchmark/tpcc/testTPCCRandom.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCRandom.cpp.s

test/benchmark/tpcc/testTPCCSchema.o: test/benchmark/tpcc/testTPCCSchema.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCSchema.o

# target to build an object file
test/benchmark/tpcc/testTPCCSchema.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCSchema.dir/build.make CMakeFiles/testTPCCSchema.dir/test/benchmark/tpcc/testTPCCSchema.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCSchema.cpp.o

test/benchmark/tpcc/testTPCCSchema.i: test/benchmark/tpcc/testTPCCSchema.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCSchema.i

# target to preprocess a source file
test/benchmark/tpcc/testTPCCSchema.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCSchema.dir/build.make CMakeFiles/testTPCCSchema.dir/test/benchmark/tpcc/testTPCCSchema.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCSchema.cpp.i

test/benchmark/tpcc/testTPCCSchema.s: test/benchmark/tpcc/testTPCCSchema.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCSchema.s

# target to generate assembly for a file
test/benchmark/tpcc/testTPCCSchema.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCSchema.dir/build.make CMakeFiles/testTPCCSchema.dir/test/benchmark/tpcc/testTPCCSchema.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCSchema.cpp.s

test/benchmark/tpcc/testTPCCTransaction.o: test/benchmark/tpcc/testTPCCTransaction.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCTransaction.o

# target to build an object file
test/benchmark/tpcc/testTPCCTransaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCTransaction.dir/build.make CMakeFiles/testTPCCTransaction.dir/test/benchmark/tpcc/testTPCCTransaction.cpp.o
.PHONY : test/benchmark/tpcc/testTPCCTransaction.cpp.o

test/benchmark/tpcc/testTPCCTransaction.i: test/benchmark/tpcc/testTPCCTransaction.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCTransaction.i

# target to preprocess a source file
test/benchmark/tpcc/testTPCCTransaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCTransaction.dir/build.make CMakeFiles/testTPCCTransaction.dir/test/benchmark/tpcc/testTPCCTransaction.cpp.i
.PHONY : test/benchmark/tpcc/testTPCCTransaction.cpp.i

test/benchmark/tpcc/testTPCCTransaction.s: test/benchmark/tpcc/testTPCCTransaction.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCTransaction.s

# target to generate assembly for a file
test/benchmark/tpcc/testTPCCTransaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTPCCTransaction.dir/build.make CMakeFiles/testTPCCTransaction.dir/test/benchmark/tpcc/testTPCCTransaction.cpp.s
.PHONY : test/benchmark/tpcc/testTPCCTransaction.cpp.s

test/benchmark/ycsb/testYCSBDatabase.o: test/benchmark/ycsb/testYCSBDatabase.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBDatabase.o

# target to build an object file
test/benchmark/ycsb/testYCSBDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBDatabase.dir/build.make CMakeFiles/testYCSBDatabase.dir/test/benchmark/ycsb/testYCSBDatabase.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBDatabase.cpp.o

test/benchmark/ycsb/testYCSBDatabase.i: test/benchmark/ycsb/testYCSBDatabase.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBDatabase.i

# target to preprocess a source file
test/benchmark/ycsb/testYCSBDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBDatabase.dir/build.make CMakeFiles/testYCSBDatabase.dir/test/benchmark/ycsb/testYCSBDatabase.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBDatabase.cpp.i

test/benchmark/ycsb/testYCSBDatabase.s: test/benchmark/ycsb/testYCSBDatabase.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBDatabase.s

# target to generate assembly for a file
test/benchmark/ycsb/testYCSBDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBDatabase.dir/build.make CMakeFiles/testYCSBDatabase.dir/test/benchmark/ycsb/testYCSBDatabase.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBDatabase.cpp.s

test/benchmark/ycsb/testYCSBQuery.o: test/benchmark/ycsb/testYCSBQuery.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBQuery.o

# target to build an object file
test/benchmark/ycsb/testYCSBQuery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBQuery.dir/build.make CMakeFiles/testYCSBQuery.dir/test/benchmark/ycsb/testYCSBQuery.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBQuery.cpp.o

test/benchmark/ycsb/testYCSBQuery.i: test/benchmark/ycsb/testYCSBQuery.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBQuery.i

# target to preprocess a source file
test/benchmark/ycsb/testYCSBQuery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBQuery.dir/build.make CMakeFiles/testYCSBQuery.dir/test/benchmark/ycsb/testYCSBQuery.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBQuery.cpp.i

test/benchmark/ycsb/testYCSBQuery.s: test/benchmark/ycsb/testYCSBQuery.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBQuery.s

# target to generate assembly for a file
test/benchmark/ycsb/testYCSBQuery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBQuery.dir/build.make CMakeFiles/testYCSBQuery.dir/test/benchmark/ycsb/testYCSBQuery.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBQuery.cpp.s

test/benchmark/ycsb/testYCSBRandom.o: test/benchmark/ycsb/testYCSBRandom.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBRandom.o

# target to build an object file
test/benchmark/ycsb/testYCSBRandom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBRandom.dir/build.make CMakeFiles/testYCSBRandom.dir/test/benchmark/ycsb/testYCSBRandom.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBRandom.cpp.o

test/benchmark/ycsb/testYCSBRandom.i: test/benchmark/ycsb/testYCSBRandom.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBRandom.i

# target to preprocess a source file
test/benchmark/ycsb/testYCSBRandom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBRandom.dir/build.make CMakeFiles/testYCSBRandom.dir/test/benchmark/ycsb/testYCSBRandom.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBRandom.cpp.i

test/benchmark/ycsb/testYCSBRandom.s: test/benchmark/ycsb/testYCSBRandom.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBRandom.s

# target to generate assembly for a file
test/benchmark/ycsb/testYCSBRandom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBRandom.dir/build.make CMakeFiles/testYCSBRandom.dir/test/benchmark/ycsb/testYCSBRandom.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBRandom.cpp.s

test/benchmark/ycsb/testYCSBSchema.o: test/benchmark/ycsb/testYCSBSchema.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBSchema.o

# target to build an object file
test/benchmark/ycsb/testYCSBSchema.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBSchema.dir/build.make CMakeFiles/testYCSBSchema.dir/test/benchmark/ycsb/testYCSBSchema.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBSchema.cpp.o

test/benchmark/ycsb/testYCSBSchema.i: test/benchmark/ycsb/testYCSBSchema.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBSchema.i

# target to preprocess a source file
test/benchmark/ycsb/testYCSBSchema.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBSchema.dir/build.make CMakeFiles/testYCSBSchema.dir/test/benchmark/ycsb/testYCSBSchema.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBSchema.cpp.i

test/benchmark/ycsb/testYCSBSchema.s: test/benchmark/ycsb/testYCSBSchema.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBSchema.s

# target to generate assembly for a file
test/benchmark/ycsb/testYCSBSchema.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBSchema.dir/build.make CMakeFiles/testYCSBSchema.dir/test/benchmark/ycsb/testYCSBSchema.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBSchema.cpp.s

test/benchmark/ycsb/testYCSBTransaction.o: test/benchmark/ycsb/testYCSBTransaction.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBTransaction.o

# target to build an object file
test/benchmark/ycsb/testYCSBTransaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBTransaction.dir/build.make CMakeFiles/testYCSBTransaction.dir/test/benchmark/ycsb/testYCSBTransaction.cpp.o
.PHONY : test/benchmark/ycsb/testYCSBTransaction.cpp.o

test/benchmark/ycsb/testYCSBTransaction.i: test/benchmark/ycsb/testYCSBTransaction.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBTransaction.i

# target to preprocess a source file
test/benchmark/ycsb/testYCSBTransaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBTransaction.dir/build.make CMakeFiles/testYCSBTransaction.dir/test/benchmark/ycsb/testYCSBTransaction.cpp.i
.PHONY : test/benchmark/ycsb/testYCSBTransaction.cpp.i

test/benchmark/ycsb/testYCSBTransaction.s: test/benchmark/ycsb/testYCSBTransaction.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBTransaction.s

# target to generate assembly for a file
test/benchmark/ycsb/testYCSBTransaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testYCSBTransaction.dir/build.make CMakeFiles/testYCSBTransaction.dir/test/benchmark/ycsb/testYCSBTransaction.cpp.s
.PHONY : test/benchmark/ycsb/testYCSBTransaction.cpp.s

test/common/testEncoder.o: test/common/testEncoder.cpp.o
.PHONY : test/common/testEncoder.o

# target to build an object file
test/common/testEncoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testEncoder.dir/build.make CMakeFiles/testEncoder.dir/test/common/testEncoder.cpp.o
.PHONY : test/common/testEncoder.cpp.o

test/common/testEncoder.i: test/common/testEncoder.cpp.i
.PHONY : test/common/testEncoder.i

# target to preprocess a source file
test/common/testEncoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testEncoder.dir/build.make CMakeFiles/testEncoder.dir/test/common/testEncoder.cpp.i
.PHONY : test/common/testEncoder.cpp.i

test/common/testEncoder.s: test/common/testEncoder.cpp.s
.PHONY : test/common/testEncoder.s

# target to generate assembly for a file
test/common/testEncoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testEncoder.dir/build.make CMakeFiles/testEncoder.dir/test/common/testEncoder.cpp.s
.PHONY : test/common/testEncoder.cpp.s

test/common/testFixedString.o: test/common/testFixedString.cpp.o
.PHONY : test/common/testFixedString.o

# target to build an object file
test/common/testFixedString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testFixedString.dir/build.make CMakeFiles/testFixedString.dir/test/common/testFixedString.cpp.o
.PHONY : test/common/testFixedString.cpp.o

test/common/testFixedString.i: test/common/testFixedString.cpp.i
.PHONY : test/common/testFixedString.i

# target to preprocess a source file
test/common/testFixedString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testFixedString.dir/build.make CMakeFiles/testFixedString.dir/test/common/testFixedString.cpp.i
.PHONY : test/common/testFixedString.cpp.i

test/common/testFixedString.s: test/common/testFixedString.cpp.s
.PHONY : test/common/testFixedString.s

# target to generate assembly for a file
test/common/testFixedString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testFixedString.dir/build.make CMakeFiles/testFixedString.dir/test/common/testFixedString.cpp.s
.PHONY : test/common/testFixedString.cpp.s

test/common/testHashMap.o: test/common/testHashMap.cpp.o
.PHONY : test/common/testHashMap.o

# target to build an object file
test/common/testHashMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testHashMap.dir/build.make CMakeFiles/testHashMap.dir/test/common/testHashMap.cpp.o
.PHONY : test/common/testHashMap.cpp.o

test/common/testHashMap.i: test/common/testHashMap.cpp.i
.PHONY : test/common/testHashMap.i

# target to preprocess a source file
test/common/testHashMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testHashMap.dir/build.make CMakeFiles/testHashMap.dir/test/common/testHashMap.cpp.i
.PHONY : test/common/testHashMap.cpp.i

test/common/testHashMap.s: test/common/testHashMap.cpp.s
.PHONY : test/common/testHashMap.s

# target to generate assembly for a file
test/common/testHashMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testHashMap.dir/build.make CMakeFiles/testHashMap.dir/test/common/testHashMap.cpp.s
.PHONY : test/common/testHashMap.cpp.s

test/common/testLockfreeQueue.o: test/common/testLockfreeQueue.cpp.o
.PHONY : test/common/testLockfreeQueue.o

# target to build an object file
test/common/testLockfreeQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testLockfreeQueue.dir/build.make CMakeFiles/testLockfreeQueue.dir/test/common/testLockfreeQueue.cpp.o
.PHONY : test/common/testLockfreeQueue.cpp.o

test/common/testLockfreeQueue.i: test/common/testLockfreeQueue.cpp.i
.PHONY : test/common/testLockfreeQueue.i

# target to preprocess a source file
test/common/testLockfreeQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testLockfreeQueue.dir/build.make CMakeFiles/testLockfreeQueue.dir/test/common/testLockfreeQueue.cpp.i
.PHONY : test/common/testLockfreeQueue.cpp.i

test/common/testLockfreeQueue.s: test/common/testLockfreeQueue.cpp.s
.PHONY : test/common/testLockfreeQueue.s

# target to generate assembly for a file
test/common/testLockfreeQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testLockfreeQueue.dir/build.make CMakeFiles/testLockfreeQueue.dir/test/common/testLockfreeQueue.cpp.s
.PHONY : test/common/testLockfreeQueue.cpp.s

test/common/testMVCCHashMap.o: test/common/testMVCCHashMap.cpp.o
.PHONY : test/common/testMVCCHashMap.o

# target to build an object file
test/common/testMVCCHashMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testMVCCHashMap.dir/build.make CMakeFiles/testMVCCHashMap.dir/test/common/testMVCCHashMap.cpp.o
.PHONY : test/common/testMVCCHashMap.cpp.o

test/common/testMVCCHashMap.i: test/common/testMVCCHashMap.cpp.i
.PHONY : test/common/testMVCCHashMap.i

# target to preprocess a source file
test/common/testMVCCHashMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testMVCCHashMap.dir/build.make CMakeFiles/testMVCCHashMap.dir/test/common/testMVCCHashMap.cpp.i
.PHONY : test/common/testMVCCHashMap.cpp.i

test/common/testMVCCHashMap.s: test/common/testMVCCHashMap.cpp.s
.PHONY : test/common/testMVCCHashMap.s

# target to generate assembly for a file
test/common/testMVCCHashMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testMVCCHashMap.dir/build.make CMakeFiles/testMVCCHashMap.dir/test/common/testMVCCHashMap.cpp.s
.PHONY : test/common/testMVCCHashMap.cpp.s

test/common/testMessage.o: test/common/testMessage.cpp.o
.PHONY : test/common/testMessage.o

# target to build an object file
test/common/testMessage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testMessage.dir/build.make CMakeFiles/testMessage.dir/test/common/testMessage.cpp.o
.PHONY : test/common/testMessage.cpp.o

test/common/testMessage.i: test/common/testMessage.cpp.i
.PHONY : test/common/testMessage.i

# target to preprocess a source file
test/common/testMessage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testMessage.dir/build.make CMakeFiles/testMessage.dir/test/common/testMessage.cpp.i
.PHONY : test/common/testMessage.cpp.i

test/common/testMessage.s: test/common/testMessage.cpp.s
.PHONY : test/common/testMessage.s

# target to generate assembly for a file
test/common/testMessage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testMessage.dir/build.make CMakeFiles/testMessage.dir/test/common/testMessage.cpp.s
.PHONY : test/common/testMessage.cpp.s

test/common/testPercentile.o: test/common/testPercentile.cpp.o
.PHONY : test/common/testPercentile.o

# target to build an object file
test/common/testPercentile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testPercentile.dir/build.make CMakeFiles/testPercentile.dir/test/common/testPercentile.cpp.o
.PHONY : test/common/testPercentile.cpp.o

test/common/testPercentile.i: test/common/testPercentile.cpp.i
.PHONY : test/common/testPercentile.i

# target to preprocess a source file
test/common/testPercentile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testPercentile.dir/build.make CMakeFiles/testPercentile.dir/test/common/testPercentile.cpp.i
.PHONY : test/common/testPercentile.cpp.i

test/common/testPercentile.s: test/common/testPercentile.cpp.s
.PHONY : test/common/testPercentile.s

# target to generate assembly for a file
test/common/testPercentile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testPercentile.dir/build.make CMakeFiles/testPercentile.dir/test/common/testPercentile.cpp.s
.PHONY : test/common/testPercentile.cpp.s

test/common/testRandom.o: test/common/testRandom.cpp.o
.PHONY : test/common/testRandom.o

# target to build an object file
test/common/testRandom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testRandom.dir/build.make CMakeFiles/testRandom.dir/test/common/testRandom.cpp.o
.PHONY : test/common/testRandom.cpp.o

test/common/testRandom.i: test/common/testRandom.cpp.i
.PHONY : test/common/testRandom.i

# target to preprocess a source file
test/common/testRandom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testRandom.dir/build.make CMakeFiles/testRandom.dir/test/common/testRandom.cpp.i
.PHONY : test/common/testRandom.cpp.i

test/common/testRandom.s: test/common/testRandom.cpp.s
.PHONY : test/common/testRandom.s

# target to generate assembly for a file
test/common/testRandom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testRandom.dir/build.make CMakeFiles/testRandom.dir/test/common/testRandom.cpp.s
.PHONY : test/common/testRandom.cpp.s

test/common/testSerialization.o: test/common/testSerialization.cpp.o
.PHONY : test/common/testSerialization.o

# target to build an object file
test/common/testSerialization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSerialization.dir/build.make CMakeFiles/testSerialization.dir/test/common/testSerialization.cpp.o
.PHONY : test/common/testSerialization.cpp.o

test/common/testSerialization.i: test/common/testSerialization.cpp.i
.PHONY : test/common/testSerialization.i

# target to preprocess a source file
test/common/testSerialization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSerialization.dir/build.make CMakeFiles/testSerialization.dir/test/common/testSerialization.cpp.i
.PHONY : test/common/testSerialization.cpp.i

test/common/testSerialization.s: test/common/testSerialization.cpp.s
.PHONY : test/common/testSerialization.s

# target to generate assembly for a file
test/common/testSerialization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSerialization.dir/build.make CMakeFiles/testSerialization.dir/test/common/testSerialization.cpp.s
.PHONY : test/common/testSerialization.cpp.s

test/common/testSocket.o: test/common/testSocket.cpp.o
.PHONY : test/common/testSocket.o

# target to build an object file
test/common/testSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSocket.dir/build.make CMakeFiles/testSocket.dir/test/common/testSocket.cpp.o
.PHONY : test/common/testSocket.cpp.o

test/common/testSocket.i: test/common/testSocket.cpp.i
.PHONY : test/common/testSocket.i

# target to preprocess a source file
test/common/testSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSocket.dir/build.make CMakeFiles/testSocket.dir/test/common/testSocket.cpp.i
.PHONY : test/common/testSocket.cpp.i

test/common/testSocket.s: test/common/testSocket.cpp.s
.PHONY : test/common/testSocket.s

# target to generate assembly for a file
test/common/testSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSocket.dir/build.make CMakeFiles/testSocket.dir/test/common/testSocket.cpp.s
.PHONY : test/common/testSocket.cpp.s

test/common/testSpinLock.o: test/common/testSpinLock.cpp.o
.PHONY : test/common/testSpinLock.o

# target to build an object file
test/common/testSpinLock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSpinLock.dir/build.make CMakeFiles/testSpinLock.dir/test/common/testSpinLock.cpp.o
.PHONY : test/common/testSpinLock.cpp.o

test/common/testSpinLock.i: test/common/testSpinLock.cpp.i
.PHONY : test/common/testSpinLock.i

# target to preprocess a source file
test/common/testSpinLock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSpinLock.dir/build.make CMakeFiles/testSpinLock.dir/test/common/testSpinLock.cpp.i
.PHONY : test/common/testSpinLock.cpp.i

test/common/testSpinLock.s: test/common/testSpinLock.cpp.s
.PHONY : test/common/testSpinLock.s

# target to generate assembly for a file
test/common/testSpinLock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSpinLock.dir/build.make CMakeFiles/testSpinLock.dir/test/common/testSpinLock.cpp.s
.PHONY : test/common/testSpinLock.cpp.s

test/common/testStringPiece.o: test/common/testStringPiece.cpp.o
.PHONY : test/common/testStringPiece.o

# target to build an object file
test/common/testStringPiece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testStringPiece.dir/build.make CMakeFiles/testStringPiece.dir/test/common/testStringPiece.cpp.o
.PHONY : test/common/testStringPiece.cpp.o

test/common/testStringPiece.i: test/common/testStringPiece.cpp.i
.PHONY : test/common/testStringPiece.i

# target to preprocess a source file
test/common/testStringPiece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testStringPiece.dir/build.make CMakeFiles/testStringPiece.dir/test/common/testStringPiece.cpp.i
.PHONY : test/common/testStringPiece.cpp.i

test/common/testStringPiece.s: test/common/testStringPiece.cpp.s
.PHONY : test/common/testStringPiece.s

# target to generate assembly for a file
test/common/testStringPiece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testStringPiece.dir/build.make CMakeFiles/testStringPiece.dir/test/common/testStringPiece.cpp.s
.PHONY : test/common/testStringPiece.cpp.s

test/common/testTime.o: test/common/testTime.cpp.o
.PHONY : test/common/testTime.o

# target to build an object file
test/common/testTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTime.dir/build.make CMakeFiles/testTime.dir/test/common/testTime.cpp.o
.PHONY : test/common/testTime.cpp.o

test/common/testTime.i: test/common/testTime.cpp.i
.PHONY : test/common/testTime.i

# target to preprocess a source file
test/common/testTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTime.dir/build.make CMakeFiles/testTime.dir/test/common/testTime.cpp.i
.PHONY : test/common/testTime.cpp.i

test/common/testTime.s: test/common/testTime.cpp.s
.PHONY : test/common/testTime.s

# target to generate assembly for a file
test/common/testTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTime.dir/build.make CMakeFiles/testTime.dir/test/common/testTime.cpp.s
.PHONY : test/common/testTime.cpp.s

test/common/testZipf.o: test/common/testZipf.cpp.o
.PHONY : test/common/testZipf.o

# target to build an object file
test/common/testZipf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testZipf.dir/build.make CMakeFiles/testZipf.dir/test/common/testZipf.cpp.o
.PHONY : test/common/testZipf.cpp.o

test/common/testZipf.i: test/common/testZipf.cpp.i
.PHONY : test/common/testZipf.i

# target to preprocess a source file
test/common/testZipf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testZipf.dir/build.make CMakeFiles/testZipf.dir/test/common/testZipf.cpp.i
.PHONY : test/common/testZipf.cpp.i

test/common/testZipf.s: test/common/testZipf.cpp.s
.PHONY : test/common/testZipf.s

# target to generate assembly for a file
test/common/testZipf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testZipf.dir/build.make CMakeFiles/testZipf.dir/test/common/testZipf.cpp.s
.PHONY : test/common/testZipf.cpp.s

test/core/testCoordinator.o: test/core/testCoordinator.cpp.o
.PHONY : test/core/testCoordinator.o

# target to build an object file
test/core/testCoordinator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCoordinator.dir/build.make CMakeFiles/testCoordinator.dir/test/core/testCoordinator.cpp.o
.PHONY : test/core/testCoordinator.cpp.o

test/core/testCoordinator.i: test/core/testCoordinator.cpp.i
.PHONY : test/core/testCoordinator.i

# target to preprocess a source file
test/core/testCoordinator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCoordinator.dir/build.make CMakeFiles/testCoordinator.dir/test/core/testCoordinator.cpp.i
.PHONY : test/core/testCoordinator.cpp.i

test/core/testCoordinator.s: test/core/testCoordinator.cpp.s
.PHONY : test/core/testCoordinator.s

# target to generate assembly for a file
test/core/testCoordinator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCoordinator.dir/build.make CMakeFiles/testCoordinator.dir/test/core/testCoordinator.cpp.s
.PHONY : test/core/testCoordinator.cpp.s

test/core/testExecutor.o: test/core/testExecutor.cpp.o
.PHONY : test/core/testExecutor.o

# target to build an object file
test/core/testExecutor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testExecutor.dir/build.make CMakeFiles/testExecutor.dir/test/core/testExecutor.cpp.o
.PHONY : test/core/testExecutor.cpp.o

test/core/testExecutor.i: test/core/testExecutor.cpp.i
.PHONY : test/core/testExecutor.i

# target to preprocess a source file
test/core/testExecutor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testExecutor.dir/build.make CMakeFiles/testExecutor.dir/test/core/testExecutor.cpp.i
.PHONY : test/core/testExecutor.cpp.i

test/core/testExecutor.s: test/core/testExecutor.cpp.s
.PHONY : test/core/testExecutor.s

# target to generate assembly for a file
test/core/testExecutor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testExecutor.dir/build.make CMakeFiles/testExecutor.dir/test/core/testExecutor.cpp.s
.PHONY : test/core/testExecutor.cpp.s

test/core/testPartitioner.o: test/core/testPartitioner.cpp.o
.PHONY : test/core/testPartitioner.o

# target to build an object file
test/core/testPartitioner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testPartitioner.dir/build.make CMakeFiles/testPartitioner.dir/test/core/testPartitioner.cpp.o
.PHONY : test/core/testPartitioner.cpp.o

test/core/testPartitioner.i: test/core/testPartitioner.cpp.i
.PHONY : test/core/testPartitioner.i

# target to preprocess a source file
test/core/testPartitioner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testPartitioner.dir/build.make CMakeFiles/testPartitioner.dir/test/core/testPartitioner.cpp.i
.PHONY : test/core/testPartitioner.cpp.i

test/core/testPartitioner.s: test/core/testPartitioner.cpp.s
.PHONY : test/core/testPartitioner.s

# target to generate assembly for a file
test/core/testPartitioner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testPartitioner.dir/build.make CMakeFiles/testPartitioner.dir/test/core/testPartitioner.cpp.s
.PHONY : test/core/testPartitioner.cpp.s

test/core/testTable.o: test/core/testTable.cpp.o
.PHONY : test/core/testTable.o

# target to build an object file
test/core/testTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTable.dir/build.make CMakeFiles/testTable.dir/test/core/testTable.cpp.o
.PHONY : test/core/testTable.cpp.o

test/core/testTable.i: test/core/testTable.cpp.i
.PHONY : test/core/testTable.i

# target to preprocess a source file
test/core/testTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTable.dir/build.make CMakeFiles/testTable.dir/test/core/testTable.cpp.i
.PHONY : test/core/testTable.cpp.i

test/core/testTable.s: test/core/testTable.cpp.s
.PHONY : test/core/testTable.s

# target to generate assembly for a file
test/core/testTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTable.dir/build.make CMakeFiles/testTable.dir/test/core/testTable.cpp.s
.PHONY : test/core/testTable.cpp.s

test/protocol/testReservation.o: test/protocol/testReservation.cpp.o
.PHONY : test/protocol/testReservation.o

# target to build an object file
test/protocol/testReservation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testReservation.dir/build.make CMakeFiles/testReservation.dir/test/protocol/testReservation.cpp.o
.PHONY : test/protocol/testReservation.cpp.o

test/protocol/testReservation.i: test/protocol/testReservation.cpp.i
.PHONY : test/protocol/testReservation.i

# target to preprocess a source file
test/protocol/testReservation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testReservation.dir/build.make CMakeFiles/testReservation.dir/test/protocol/testReservation.cpp.i
.PHONY : test/protocol/testReservation.cpp.i

test/protocol/testReservation.s: test/protocol/testReservation.cpp.s
.PHONY : test/protocol/testReservation.s

# target to generate assembly for a file
test/protocol/testReservation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testReservation.dir/build.make CMakeFiles/testReservation.dir/test/protocol/testReservation.cpp.s
.PHONY : test/protocol/testReservation.cpp.s

test/protocol/testScarHelper.o: test/protocol/testScarHelper.cpp.o
.PHONY : test/protocol/testScarHelper.o

# target to build an object file
test/protocol/testScarHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testScarHelper.dir/build.make CMakeFiles/testScarHelper.dir/test/protocol/testScarHelper.cpp.o
.PHONY : test/protocol/testScarHelper.cpp.o

test/protocol/testScarHelper.i: test/protocol/testScarHelper.cpp.i
.PHONY : test/protocol/testScarHelper.i

# target to preprocess a source file
test/protocol/testScarHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testScarHelper.dir/build.make CMakeFiles/testScarHelper.dir/test/protocol/testScarHelper.cpp.i
.PHONY : test/protocol/testScarHelper.cpp.i

test/protocol/testScarHelper.s: test/protocol/testScarHelper.cpp.s
.PHONY : test/protocol/testScarHelper.s

# target to generate assembly for a file
test/protocol/testScarHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testScarHelper.dir/build.make CMakeFiles/testScarHelper.dir/test/protocol/testScarHelper.cpp.s
.PHONY : test/protocol/testScarHelper.cpp.s

test/protocol/testScarRWKey.o: test/protocol/testScarRWKey.cpp.o
.PHONY : test/protocol/testScarRWKey.o

# target to build an object file
test/protocol/testScarRWKey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testScarRWKey.dir/build.make CMakeFiles/testScarRWKey.dir/test/protocol/testScarRWKey.cpp.o
.PHONY : test/protocol/testScarRWKey.cpp.o

test/protocol/testScarRWKey.i: test/protocol/testScarRWKey.cpp.i
.PHONY : test/protocol/testScarRWKey.i

# target to preprocess a source file
test/protocol/testScarRWKey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testScarRWKey.dir/build.make CMakeFiles/testScarRWKey.dir/test/protocol/testScarRWKey.cpp.i
.PHONY : test/protocol/testScarRWKey.cpp.i

test/protocol/testScarRWKey.s: test/protocol/testScarRWKey.cpp.s
.PHONY : test/protocol/testScarRWKey.s

# target to generate assembly for a file
test/protocol/testScarRWKey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testScarRWKey.dir/build.make CMakeFiles/testScarRWKey.dir/test/protocol/testScarRWKey.cpp.s
.PHONY : test/protocol/testScarRWKey.cpp.s

test/protocol/testSiloRWKey.o: test/protocol/testSiloRWKey.cpp.o
.PHONY : test/protocol/testSiloRWKey.o

# target to build an object file
test/protocol/testSiloRWKey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSiloRWKey.dir/build.make CMakeFiles/testSiloRWKey.dir/test/protocol/testSiloRWKey.cpp.o
.PHONY : test/protocol/testSiloRWKey.cpp.o

test/protocol/testSiloRWKey.i: test/protocol/testSiloRWKey.cpp.i
.PHONY : test/protocol/testSiloRWKey.i

# target to preprocess a source file
test/protocol/testSiloRWKey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSiloRWKey.dir/build.make CMakeFiles/testSiloRWKey.dir/test/protocol/testSiloRWKey.cpp.i
.PHONY : test/protocol/testSiloRWKey.cpp.i

test/protocol/testSiloRWKey.s: test/protocol/testSiloRWKey.cpp.s
.PHONY : test/protocol/testSiloRWKey.s

# target to generate assembly for a file
test/protocol/testSiloRWKey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testSiloRWKey.dir/build.make CMakeFiles/testSiloRWKey.dir/test/protocol/testSiloRWKey.cpp.s
.PHONY : test/protocol/testSiloRWKey.cpp.s

test/protocol/testTwoPLHelper.o: test/protocol/testTwoPLHelper.cpp.o
.PHONY : test/protocol/testTwoPLHelper.o

# target to build an object file
test/protocol/testTwoPLHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTwoPLHelper.dir/build.make CMakeFiles/testTwoPLHelper.dir/test/protocol/testTwoPLHelper.cpp.o
.PHONY : test/protocol/testTwoPLHelper.cpp.o

test/protocol/testTwoPLHelper.i: test/protocol/testTwoPLHelper.cpp.i
.PHONY : test/protocol/testTwoPLHelper.i

# target to preprocess a source file
test/protocol/testTwoPLHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTwoPLHelper.dir/build.make CMakeFiles/testTwoPLHelper.dir/test/protocol/testTwoPLHelper.cpp.i
.PHONY : test/protocol/testTwoPLHelper.cpp.i

test/protocol/testTwoPLHelper.s: test/protocol/testTwoPLHelper.cpp.s
.PHONY : test/protocol/testTwoPLHelper.s

# target to generate assembly for a file
test/protocol/testTwoPLHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTwoPLHelper.dir/build.make CMakeFiles/testTwoPLHelper.dir/test/protocol/testTwoPLHelper.cpp.s
.PHONY : test/protocol/testTwoPLHelper.cpp.s

test/protocol/testTwoPLRWKey.o: test/protocol/testTwoPLRWKey.cpp.o
.PHONY : test/protocol/testTwoPLRWKey.o

# target to build an object file
test/protocol/testTwoPLRWKey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTwoPLRWKey.dir/build.make CMakeFiles/testTwoPLRWKey.dir/test/protocol/testTwoPLRWKey.cpp.o
.PHONY : test/protocol/testTwoPLRWKey.cpp.o

test/protocol/testTwoPLRWKey.i: test/protocol/testTwoPLRWKey.cpp.i
.PHONY : test/protocol/testTwoPLRWKey.i

# target to preprocess a source file
test/protocol/testTwoPLRWKey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTwoPLRWKey.dir/build.make CMakeFiles/testTwoPLRWKey.dir/test/protocol/testTwoPLRWKey.cpp.i
.PHONY : test/protocol/testTwoPLRWKey.cpp.i

test/protocol/testTwoPLRWKey.s: test/protocol/testTwoPLRWKey.cpp.s
.PHONY : test/protocol/testTwoPLRWKey.s

# target to generate assembly for a file
test/protocol/testTwoPLRWKey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testTwoPLRWKey.dir/build.make CMakeFiles/testTwoPLRWKey.dir/test/protocol/testTwoPLRWKey.cpp.s
.PHONY : test/protocol/testTwoPLRWKey.cpp.s

test/testJemalloc.o: test/testJemalloc.cpp.o
.PHONY : test/testJemalloc.o

# target to build an object file
test/testJemalloc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testJemalloc.dir/build.make CMakeFiles/testJemalloc.dir/test/testJemalloc.cpp.o
.PHONY : test/testJemalloc.cpp.o

test/testJemalloc.i: test/testJemalloc.cpp.i
.PHONY : test/testJemalloc.i

# target to preprocess a source file
test/testJemalloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testJemalloc.dir/build.make CMakeFiles/testJemalloc.dir/test/testJemalloc.cpp.i
.PHONY : test/testJemalloc.cpp.i

test/testJemalloc.s: test/testJemalloc.cpp.s
.PHONY : test/testJemalloc.s

# target to generate assembly for a file
test/testJemalloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testJemalloc.dir/build.make CMakeFiles/testJemalloc.dir/test/testJemalloc.cpp.s
.PHONY : test/testJemalloc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... format"
	@echo "... bench_tpcc"
	@echo "... bench_ycsb"
	@echo "... common"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... testCoordinator"
	@echo "... testDatabaseTableID"
	@echo "... testEncoder"
	@echo "... testExecutor"
	@echo "... testFixedString"
	@echo "... testHashMap"
	@echo "... testJemalloc"
	@echo "... testLockfreeQueue"
	@echo "... testMVCCHashMap"
	@echo "... testMessage"
	@echo "... testPartitioner"
	@echo "... testPercentile"
	@echo "... testRandom"
	@echo "... testReservation"
	@echo "... testScarHelper"
	@echo "... testScarRWKey"
	@echo "... testSerialization"
	@echo "... testSiloRWKey"
	@echo "... testSocket"
	@echo "... testSpinLock"
	@echo "... testStringPiece"
	@echo "... testTPCCDatabase"
	@echo "... testTPCCQuery"
	@echo "... testTPCCRandom"
	@echo "... testTPCCSchema"
	@echo "... testTPCCTransaction"
	@echo "... testTable"
	@echo "... testTime"
	@echo "... testTwoPLHelper"
	@echo "... testTwoPLRWKey"
	@echo "... testYCSBDatabase"
	@echo "... testYCSBQuery"
	@echo "... testYCSBRandom"
	@echo "... testYCSBSchema"
	@echo "... testYCSBTransaction"
	@echo "... testZipf"
	@echo "... bench_tpcc.o"
	@echo "... bench_tpcc.i"
	@echo "... bench_tpcc.s"
	@echo "... bench_ycsb.o"
	@echo "... bench_ycsb.i"
	@echo "... bench_ycsb.s"
	@echo "... common/Time.o"
	@echo "... common/Time.i"
	@echo "... common/Time.s"
	@echo "... test/benchmark/testDatabaseTableID.o"
	@echo "... test/benchmark/testDatabaseTableID.i"
	@echo "... test/benchmark/testDatabaseTableID.s"
	@echo "... test/benchmark/tpcc/testTPCCDatabase.o"
	@echo "... test/benchmark/tpcc/testTPCCDatabase.i"
	@echo "... test/benchmark/tpcc/testTPCCDatabase.s"
	@echo "... test/benchmark/tpcc/testTPCCQuery.o"
	@echo "... test/benchmark/tpcc/testTPCCQuery.i"
	@echo "... test/benchmark/tpcc/testTPCCQuery.s"
	@echo "... test/benchmark/tpcc/testTPCCRandom.o"
	@echo "... test/benchmark/tpcc/testTPCCRandom.i"
	@echo "... test/benchmark/tpcc/testTPCCRandom.s"
	@echo "... test/benchmark/tpcc/testTPCCSchema.o"
	@echo "... test/benchmark/tpcc/testTPCCSchema.i"
	@echo "... test/benchmark/tpcc/testTPCCSchema.s"
	@echo "... test/benchmark/tpcc/testTPCCTransaction.o"
	@echo "... test/benchmark/tpcc/testTPCCTransaction.i"
	@echo "... test/benchmark/tpcc/testTPCCTransaction.s"
	@echo "... test/benchmark/ycsb/testYCSBDatabase.o"
	@echo "... test/benchmark/ycsb/testYCSBDatabase.i"
	@echo "... test/benchmark/ycsb/testYCSBDatabase.s"
	@echo "... test/benchmark/ycsb/testYCSBQuery.o"
	@echo "... test/benchmark/ycsb/testYCSBQuery.i"
	@echo "... test/benchmark/ycsb/testYCSBQuery.s"
	@echo "... test/benchmark/ycsb/testYCSBRandom.o"
	@echo "... test/benchmark/ycsb/testYCSBRandom.i"
	@echo "... test/benchmark/ycsb/testYCSBRandom.s"
	@echo "... test/benchmark/ycsb/testYCSBSchema.o"
	@echo "... test/benchmark/ycsb/testYCSBSchema.i"
	@echo "... test/benchmark/ycsb/testYCSBSchema.s"
	@echo "... test/benchmark/ycsb/testYCSBTransaction.o"
	@echo "... test/benchmark/ycsb/testYCSBTransaction.i"
	@echo "... test/benchmark/ycsb/testYCSBTransaction.s"
	@echo "... test/common/testEncoder.o"
	@echo "... test/common/testEncoder.i"
	@echo "... test/common/testEncoder.s"
	@echo "... test/common/testFixedString.o"
	@echo "... test/common/testFixedString.i"
	@echo "... test/common/testFixedString.s"
	@echo "... test/common/testHashMap.o"
	@echo "... test/common/testHashMap.i"
	@echo "... test/common/testHashMap.s"
	@echo "... test/common/testLockfreeQueue.o"
	@echo "... test/common/testLockfreeQueue.i"
	@echo "... test/common/testLockfreeQueue.s"
	@echo "... test/common/testMVCCHashMap.o"
	@echo "... test/common/testMVCCHashMap.i"
	@echo "... test/common/testMVCCHashMap.s"
	@echo "... test/common/testMessage.o"
	@echo "... test/common/testMessage.i"
	@echo "... test/common/testMessage.s"
	@echo "... test/common/testPercentile.o"
	@echo "... test/common/testPercentile.i"
	@echo "... test/common/testPercentile.s"
	@echo "... test/common/testRandom.o"
	@echo "... test/common/testRandom.i"
	@echo "... test/common/testRandom.s"
	@echo "... test/common/testSerialization.o"
	@echo "... test/common/testSerialization.i"
	@echo "... test/common/testSerialization.s"
	@echo "... test/common/testSocket.o"
	@echo "... test/common/testSocket.i"
	@echo "... test/common/testSocket.s"
	@echo "... test/common/testSpinLock.o"
	@echo "... test/common/testSpinLock.i"
	@echo "... test/common/testSpinLock.s"
	@echo "... test/common/testStringPiece.o"
	@echo "... test/common/testStringPiece.i"
	@echo "... test/common/testStringPiece.s"
	@echo "... test/common/testTime.o"
	@echo "... test/common/testTime.i"
	@echo "... test/common/testTime.s"
	@echo "... test/common/testZipf.o"
	@echo "... test/common/testZipf.i"
	@echo "... test/common/testZipf.s"
	@echo "... test/core/testCoordinator.o"
	@echo "... test/core/testCoordinator.i"
	@echo "... test/core/testCoordinator.s"
	@echo "... test/core/testExecutor.o"
	@echo "... test/core/testExecutor.i"
	@echo "... test/core/testExecutor.s"
	@echo "... test/core/testPartitioner.o"
	@echo "... test/core/testPartitioner.i"
	@echo "... test/core/testPartitioner.s"
	@echo "... test/core/testTable.o"
	@echo "... test/core/testTable.i"
	@echo "... test/core/testTable.s"
	@echo "... test/protocol/testReservation.o"
	@echo "... test/protocol/testReservation.i"
	@echo "... test/protocol/testReservation.s"
	@echo "... test/protocol/testScarHelper.o"
	@echo "... test/protocol/testScarHelper.i"
	@echo "... test/protocol/testScarHelper.s"
	@echo "... test/protocol/testScarRWKey.o"
	@echo "... test/protocol/testScarRWKey.i"
	@echo "... test/protocol/testScarRWKey.s"
	@echo "... test/protocol/testSiloRWKey.o"
	@echo "... test/protocol/testSiloRWKey.i"
	@echo "... test/protocol/testSiloRWKey.s"
	@echo "... test/protocol/testTwoPLHelper.o"
	@echo "... test/protocol/testTwoPLHelper.i"
	@echo "... test/protocol/testTwoPLHelper.s"
	@echo "... test/protocol/testTwoPLRWKey.o"
	@echo "... test/protocol/testTwoPLRWKey.i"
	@echo "... test/protocol/testTwoPLRWKey.s"
	@echo "... test/testJemalloc.o"
	@echo "... test/testJemalloc.i"
	@echo "... test/testJemalloc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

